

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task_manager"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@exampl1.com
      PGADMIN_DEFAULT_PASSWORD: Admin@Secure123
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5050:80"
    networks:
      - app-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task_manager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9090:9090"
    networks:
      - app-network
    command: ["./wait-for-db.sh", "db:5432", "--", "java", "-jar", "app.jar"]

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: